openapi: 3.0.0
info:
  title: API MARKETPLACE
  version: '1.0'
  contact:
    email: anymarketdev@db1.com.br
    name: AnyMarket Developers
    url: 'http://developers.anymarket.com.br/'
  x-logo:
    url: 'https://anymarket.com.br/wp-content/uploads/2018/07/icon-anymarket-300x300.png'
  x-preferred: true
  x-providerName: API MARKETPLACE
  description: |
    Nesse conjunto de chamadas irá conter as chamadas necessárias que o marketplace precisa realizar na camada ANYMARKET afim de obter dados como:

    - Informações sobre produto;
    - Informação de atualização de dados das transmissões;
    - Atualizar status de transmissões;
    - Inserir pedidos;
    - Informação de dados do pedido;
    - Atualizar informações de pedidos;
    - Cotação de frete;
    - Monitoramento;
servers:
  - url: 'http://sandbox-api.anymarket.com.br/marketplace/api'
    description: Sandbox
paths:
  '/skumarketplace/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: Atualizar dados da transmissão.
      operationId: put-skumarketplace-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      idSku:
                        type: integer
                        format: int64
                        minimum: 0
                        exclusiveMaximum: true
                  - $ref: ./remote_pt.yaml#/components/schemas/SkuMarketplace
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SkuMarketPlacePut'
      description: Atualizar dados da transmissão.
      tags:
        - Anúncios
    get:
      summary: '/skumarketplace/{id}'
      tags:
        - Anúncios
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuMarketplace'
      operationId: get-skumarketplace-id
      parameters:
        - $ref: '#/components/parameters/appId'
        - $ref: '#/components/parameters/token'
      description: Consulta os dados do anúncio no ANYMARKET.
  /configuration:
    get:
      summary: /configuration
      tags:
        - Configuração
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configuration'
      operationId: get-api-configuration
      description: Consulta todas as configurações realizadas pelo seller no ANYMARKET.
      parameters:
        - schema:
            type: string
          in: header
          name: appId
        - schema:
            type: string
          in: header
          name: token
    parameters: []
  '/configuration/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Código de configuração gerado pelo Anymarket
    get:
      summary: '/configuration/{id}'
      tags:
        - Configuração
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configuration'
      operationId: get-api-configuration-id
      description: Consulta pelo ID da conta as configurações realizadas pelo seller no ANYMARKET.
      parameters:
        - schema:
            type: string
          in: header
          name: appId
          required: true
        - schema:
            type: string
          in: header
          name: token
          required: true
  '/orders/{marketPlaceId}/transmissionStatus':
    parameters:
      - schema:
          type: string
        name: marketPlaceId
        in: path
        required: true
    put:
      summary: '/orders/{marketPlaceId}/transmissionStatus'
      tags:
        - Pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: put-orders-id-transmissionStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderStatusUpdate'
      description: |-
        Quando o marketplace receber a notificação de atualização de um pedido, seja ele mudando para FATURADO, ENVIADO, CONCLUIDO ou CANCELADO no endpoint /updateOrderStatusInMarketPlace. 

        Necessariamente o marketplace deve realizar o GET para consultar os dados do pedido e na sequencia utilizar do endpoint citado a cima, removendo a sinalização de sincronização e identificando qual o status do pedido no marketplace. 

        Lembrando que caso não processe, o erro deve ser informado também nesse endpoint.
      parameters:
        - schema:
            type: string
          in: header
          name: appId
          required: true
        - schema:
            type: string
          in: header
          name: token
          required: true
  /orders:
    post:
      summary: Criando um pedido no ANYMARKET
      operationId: post-orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
              examples:
                Example - 1:
                  value:
                    code: '400'
                    message: Erro ao criar o recurso. Somente é possivel criar recurso com status x ou y.
                Example - 2:
                  value:
                    code: '400'
                    message: 'Erro ao criar o pedido. Já existe um pedido com id [%s].'
      parameters:
        - schema:
            type: boolean
          in: query
          name: orderNewPattern
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderPost'
      tags:
        - Pedidos
    get:
      summary: /orders
      operationId: get-orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_Order'
      tags:
        - Pedidos
      description: Obtém todos os pedidos do marketplace na base do cliente.
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/sort'
        - schema:
            type: string
            enum:
              - PENDING
              - PAID
              - INVOICED
              - SHIPPED
              - DELIVERED
              - CANCELED
          in: query
          name: status
          description: Status do pedido
        - schema:
            type: string
            format: date-time
          in: query
          name: createdAfter
          description: Data da criação do pedido
        - schema:
            type: string
          in: header
          name: appId
          required: true
        - schema:
            type: string
          in: header
          name: token
          required: true
  '/orders/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Código do pedido gerado pelo Anymarket
    get:
      summary: '/orders/{marketPlaceId}'
      tags:
        - Pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: get-orders-id
      description: Consulta os detalhes de um pedido
      parameters:
        - schema:
            type: string
          in: header
          name: appId
          required: true
        - schema:
            type: string
          in: header
          name: token
          required: true
  '/orders/{marketPlaceId}/markAsPaid':
    parameters:
      - schema:
          type: string
        name: marketPlaceId
        in: path
        required: true
        description: Id do pedido no marketplace
    put:
      summary: '/orders/{marketPlaceId}/markAsPaid'
      tags:
        - Pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: put-orders-id-markAsPaid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CanceledStatusDTO'
            examples:
              example-1:
                value:
                  date: '2021-01-11T13:48:55-03:00:00'
      description: Utilizado para que o middleware marque o pedido como PAGO no ANYMARKET.
      parameters:
        - schema:
            type: string
          in: header
          name: appId
        - schema:
            type: string
          in: header
          name: token
  '/orders/{marketPlaceId}/markAsCanceled':
    parameters:
      - schema:
          type: string
        name: marketPlaceId
        in: path
        required: true
    put:
      summary: '/orders/{marketPlaceId}/markAsCanceled'
      tags:
        - Pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: put-id-markAsCanceled
      description: Utilizado para que o middleware marque o pedido como CANCELADO no ANYMARKET.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CanceledStatusDTO'
            examples:
              example-1:
                value:
                  date: '2021-01-11T13:48:55-03:00:00'
      parameters:
        - schema:
            type: string
          in: header
          name: appId
          required: true
        - schema:
            type: string
          in: header
          name: token
          required: true
    description: Marcar pedido como Cancelado
  '/orders/{marketPlaceId}/markAsInvoiced':
    parameters:
      - schema:
          type: string
        name: marketPlaceId
        in: path
        required: true
    put:
      summary: '/orders/{marketPlaceId}/markAsInvoiced'
      tags:
        - Pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: put-orders-id-markAsInvoiced
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CanceledStatusDTO'
            examples:
              example-1:
                value:
                  date: '2020-01-11T13:48:55-03:00:00'
      description: |-
        Utilizado para que o middleware marque o pedido como FATURADO no ANYMARKET.

        Apenas utilizado quando o marketplace possui formas de envios próprias, como modalidade fulfillment ou emissão de etiquetas. 
      parameters:
        - schema:
            type: string
          in: header
          name: appId
          required: true
        - schema:
            type: string
          in: header
          name: token
          required: true
  '/orders/{marketPlaceId}/markAsShipped':
    parameters:
      - schema:
          type: string
        name: marketPlaceId
        in: path
        required: true
    put:
      summary: '/orders/{marketPlaceId}/markAsShipped'
      tags:
        - Pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: put-id-markAsShipped
      description: |-
        Utilizado para que o middleware marque o pedido como ENVIADO no ANYMARKET.

        Apenas utilizado quando o marketplace possui formas de envios próprias, como modalidade fulfillment ou emissão de etiquetas. 
      parameters:
        - in: header
          name: appId
          required: true
        - in: header
          name: token
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/markAsShipped'
            examples:
              example-1:
                value:
                  status: SHIPPED
                  url: string
                  number: string
                  carrier: string
                  estimateDate: string
                  shippedDate: string
  '/orders/{marketPlaceId}/markAsDelivered':
    parameters:
      - schema:
          type: string
        name: marketPlaceId
        in: path
        required: true
    put:
      summary: '/orders/{marketPlaceId}/markAsDelivered'
      tags:
        - Pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: put-orders-id-markAsDelivered
      description: |-
        Utilizado para que o middleware marque o pedido como ENTREGUE no ANYMARKET.

        Apenas utilizado quando o marketplace possui formas de envios próprias, como modalidade fulfillment ou emissão de etiquetas.
      parameters:
        - in: header
          name: appId
          description: 'Identificador único do marketplace, fornecido pela equipe ANYMARKET.'
          required: true
          schema: {}
        - in: header
          name: token
          description: 'Identificador do lojista, fornecido pelo ANYMARKET para os lojistas.'
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/markAsDelivered'
            examples:
              example-1:
                value:
                  deliveredDate: string
          application/xml:
            schema:
              $ref: '#/components/schemas/markAsDelivered'
            examples:
              example-1:
                value: '[object Object]'
        description: ''
components:
  securitySchemes: {}
  schemas:
    '400':
      description: ''
      type: object
      x-examples:
        example-1:
          value:
            code: '400'
            message: Erro ao criar o recurso. Somente é possivel criar recurso com status x ou y.
      properties:
        code:
          type: string
          minLength: 1
        message:
          type: string
          minLength: 1
      examples:
        - code: '400'
          message: Erro ao criar o recurso. Somente é possivel criar recurso com status x ou y.
      x-tags:
        - erro
      title: 400 - Error
    '404':
      description: ''
      type: object
      x-examples:
        example-1:
          value:
            code: '404'
            message: Recurso com o id 'xxx' não encontrado.
      properties:
        code:
          type: string
          minLength: 1
        message:
          type: string
          minLength: 1
      examples:
        - code: '404'
          message: Recurso com o id 'xxx' não encontrado.
      x-tags:
        - erro
      title: 404 - Error
    '422':
      description: ''
      type: object
      x-examples:
        example-1:
          value:
            code: '422'
            message: O campo informado esta fora das especificações.
      properties:
        code:
          type: string
          minLength: 1
        message:
          type: string
          minLength: 1
      examples:
        - code: '422'
          message: O campo informado esta fora das especificações.
      x-tags:
        - erro
      title: 422 - Error
    '500':
      description: ''
      type: object
      x-examples:
        example-1:
          value:
            code: '500'
            message: Internal Server Error
      properties:
        code:
          type: string
          minLength: 1
        message:
          type: string
          minLength: 1
      examples:
        - code: '500'
          message: Internal Server Error
      x-tags:
        - erro
      title: 500 - Error
    SkuMarketplace:
      description: ''
      examples:
        - id: 0
          idInMarketplace: string
          marketPlace: B2W
          index: 0
          publicationStatus: string
          marketplaceStatus: string
          transmissionStatus: string
          errorMsg: string
          skuMarketPlaceMessage:
            message: string
            key: string
            parameters:
              parameter1: value1
              parameter2: value2
          price: 0
          priceFactor: 1
          discountPrice: 0
          skuInMarketplace: string
          marketplaceItemCode: string
          fields:
            title: string
            template: string
            priceFactor: string
            DISCOUNT_TYPE: string
            DISCOUNT_VALUE: string
            HAS_DISCOUNT: string
            CONCAT_ATTRIBUTES: string
            delivery_type: string
            SHIPMENT: string
            crossDocking: string
            CUSTOM_DESCRIPTION: string
            EAN: string
            MANUFACTURING_TIME: string
            VALUE: string
            PERCENT: string
            bronze_price: string
            bronze_price_factor: string
            buying_mode: string
            category_with_variation: string
            condition: string
            free_price: string
            free_price_factor: string
            free_shipping: string
            gold_premium_price: string
            gold_premium_price_factor: string
            gold_price: string
            gold_price_factor: string
            gold_pro_price: string
            gold_pro_price_factor: string
            gold_special_price: string
            gold_special_price_factor: string
            listing_type_id: string
            shipping_local_pick_up: string
            shipping_mode: string
            silver_price: string
            silver_price_factor: string
          availableStock:
            amount: 0
            availableAmount: 0
            cost: 0
            totalReservation: 0
            physicalAmount: 0
            reservedPending: 0
            reservedPaid: 0
            totalInInvoicedStatus: 0
            stockLocal: string
            additionalTime: 0
          attributes:
            cor: azul
            tamanho: grande
            material: inox
          idAccount: 0
          accountName: string
          origin: BIND
          isCatalog: true
          permalink: string
          title: string
          ean: string
      title: SkuMarketplace
      x-examples:
        example-1:
          value:
            id: -9223372036854776000
            idInMarketplace: string
            marketPlace: string
            index: 0
            publicationStatus: string
            marketplaceStatus: string
            transmissionStatus: string
            errorMsg: string
            skuMarketPlaceMessage:
              message: string
              key: string
              parameters:
                parameter1: value1
                parameter2: value2
            price: 0
            priceFactor: 0
            discountPrice: 0
            skuInMarketplace: string
            marketplaceItemCode: string
            fields:
              title: string
              template: string
              priceFactor: string
              DISCOUNT_TYPE: string
              DISCOUNT_VALUE: string
              HAS_DISCOUNT: string
              CONCAT_ATTRIBUTES: string
              delivery_type: string
              SHIPMENT: string
              crossDocking: string
              CUSTOM_DESCRIPTION: string
              EAN: string
              MANUFACTURING_TIME: string
              VALUE: string
              PERCENT: string
              bronze_price: string
              bronze_price_factor: string
              buying_mode: string
              category_with_variation: string
              condition: string
              free_price: string
              free_price_factor: string
              free_shipping: string
              gold_premium_price: string
              gold_premium_price_factor: string
              gold_price: string
              gold_price_factor: string
              gold_pro_price: string
              gold_pro_price_factor: string
              gold_special_price: string
              gold_special_price_factor: string
              listing_type_id: string
              shipping_local_pick_up: string
              shipping_mode: string
              silver_price: string
              silver_price_factor: string
            availableStock:
              amount: 0
              availableAmount: 0
              cost: 0
              totalReservation: 0
              physicalAmount: 0
              reservedPending: 0
              reservedPaid: 0
              totalInInvoicedStatus: 0
              stockLocal: string
              additionalTime: 0
            attributes:
              cor: azul
              tamanho: grande
              material: inox
            idAccount: 0
            accountName: string
            origin: BIND
            isCatalog: true
            permalink: string
            title: string
            ean: string
            status: string
            idInSite: string
            endDate: '2019-08-24T14:15:22Z'
            stock:
              amount: 0
              availableAmount: 0
              cost: 0
              totalReservation: 0
              physicalAmount: 0
              reservedPending: 0
              reservedPaid: 0
              totalInInvoicedStatus: 0
              stockLocal: string
              additionalTime: 0
            sku:
              id: -9223372036854776000
              partnerId: string
              amount: 0
              ean: string
              title: string
              price: 0
              sellPrice: 0
              additionalTime: 0
              variations:
                - id: 0
                  idInMarketplace: string
                  description: string
                  type:
                    id: 0
                    idInMarketplace: string
                    name: string
                    partnerId: string
                    visualVariation: true
                  partnerId: string
              product:
                id: 0
                title: string
                description: string
                model: string
                nbm:
                  id: string
                  description: string
                videoUrl: string
                definitionPriceScope: COST
                characteristics:
                  - index: 0
                    name: string
                    value: string
                origin:
                  id: 0
                  name: NACIONAL
                category:
                  id: 0
                  idInMarketplace: string
                  name: string
                  path: string
                height: 0
                length: 0
                width: 0
                weight: 0
                images:
                  - id: 0
                    index: 0
                    variation: string
                    thumbnailUrl: string
                    standardUrl: string
                    lowResolutionUrl: string
                    originalImage: string
                    url: string
                    statusMessage: string
                    status: UNPROCESSED
                    main: true
                    standardWidth: string
                    standardHeight: string
                    originalWidth: string
                    originalHeight: string
                brand:
                  id: 0
                  idInMarketplace: string
                  name: string
                  partnerId: string
                warrantyTime: 0
                warrantyText: string
                priceFactor: 0
                calculatedPrice: true
                hasVariations: true
                gender: MALE
                allowAutomaticSkuMarketplaceCreation: true
            mainSkuMarketplace: 0
      allOf:
        - $ref: '#/components/schemas/SkuMarketPlaceBase'
        - properties:
            id:
              type: integer
              description: Id do anúncio no ANYMARKET
              format: int64
            stock:
              $ref: ./remote_pt.yaml#/components/schemas/Stock
            attributes:
              $ref: ./remote_pt.yaml#/components/schemas/Attributes
            sku:
              $ref: ./remote_pt.yaml#/components/schemas/SKU
            mainSkuMarketplace:
              type: integer
              description: Status da publicação
              format: int64
              minimum: 0
              exclusiveMaximum: true
      required:
        - id
        - attributes
        - sku
        - mainSkuMarketplace
    SkuMarketPlacePut:
      title: SkuMarketPlacePut
      type: object
      properties:
        idInMarketplace:
          type: string
        status:
          type: string
        marketplaceStatus:
          type: string
        transmissionStatus:
          type: string
        errorMsg:
          type: string
        skuMarketPlaceMessage:
          $ref: ./remote_pt.yaml#/components/schemas/SkuMarketPlaceMessage
        idInSite:
          type: string
        fields:
          $ref: ./remote_pt.yaml#/components/schemas/SkuMarketplaceField
        isCatalog:
          type: boolean
        permalink:
          type: string
        endDate:
          type: string
          format: date-time
    SkuMarketPlaceBase:
      title: SkuMarketPlaceBase
      x-examples: {}
      allOf:
        - $ref: '#/components/schemas/SkuMarketPlacePut'
        - properties:
            title:
              type: string
            ean:
              type: string
            skuInMarketplace:
              type: string
            priceFactor:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            price:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            discountPrice:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            idAccount:
              type: integer
              format: int64
              minimum: 0
              exclusiveMaximum: true
            accountName:
              type: string
            marketPlace:
              type: string
    OrderPut:
      title: OrderPut
      type: object
      properties:
        marketPlaceUrl:
          type: string
        marketPlaceStatus:
          type: string
        marketPlaceStatusComplement:
          type: string
        shipping:
          $ref: ./remote_pt.yaml#/components/schemas/ApiShipping
        billingAddress:
          $ref: ./remote_pt.yaml#/components/schemas/ApiBillingAddress
        buyer:
          $ref: ./remote_pt.yaml#/components/schemas/ApiBuyer
        payments:
          type: array
          items:
            $ref: ./remote_pt.yaml#/components/schemas/ApiPayment
        observation:
          type: string
        anymarketAddress:
          $ref: ./remote_pt.yaml#/components/schemas/ApiAnymarketOrderAddress
        tracking:
          $ref: ./remote_pt.yaml#/components/schemas/ApiTracking
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        documentIntermediator:
          type: string
        intermediateRegistrationId:
          type: string
        documentPaymentInstitution:
          type: string
        subChannel:
          type: string
        subChannelNormalized:
          type: string
    OrderItem:
      title: OrderItem
      type: object
      properties:
        partnerId:
          type: string
        sku:
          type: object
          properties:
            partnerId:
              type: string
        amount:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        unit:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        gross:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        total:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        discount:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        shippings:
          type: array
          items:
            $ref: ./remote_pt.yaml#/components/schemas/ApiOrderItemShipping
        marketPlaceId:
          type: string
        orderItemId:
          type: integer
          format: int64
          minimum: 0
          exclusiveMaximum: true
    OrderPost:
      title: OrderPost
      allOf:
        - type: object
          properties:
            marketPlaceId:
              type: string
            marketPlaceNumber:
              type: string
            createdAt:
              type: string
              format: date-time
            discount:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            freight:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            productNet:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            gross:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            total:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            interestValue:
              type: number
              format: double
              minimum: 0
              exclusiveMaximum: true
            items:
              format: double
              type: array
              items:
                $ref: '#/components/schemas/OrderItem'
            idAccount:
              type: integer
              format: int64
              minimum: 0
              exclusiveMaximum: true
            accountName:
              type: string
            status:
              type: string
              enum:
                - PENDING
                - PAID
                - INVOICED
                - SHIPPED
                - DELIVERED
                - CANCELED
            subChannel:
              type: string
            subChannelNormalized:
              type: string
        - $ref: '#/components/schemas/OrderPut'
      x-examples: {}
      description: ''
    Invoice:
      title: Invoice
      type: object
      properties:
        accessKey:
          type: string
        series:
          type: string
        number:
          type: string
        date:
          type: string
          format: date-time
        linkNfe:
          type: string
          format: date-time
        invoiceLink:
          type: string
        cfop:
          type: string
    Order:
      title: Order
      allOf:
        - type: object
          properties:
            id:
              type: integer
              format: int64
              minimum: 0
              exclusiveMaximum: true
            partnerId:
              type: string
            paymentDate:
              type: string
              format: date-time
            cancelDate:
              type: string
              format: date-time
            cancellationCode:
              type: string
              enum:
                - WITHOUT_STOCK
                - SHIPPING_ADDRESS
                - CUSTOMER_EXCHANGE
                - GENERAL_ADJUSTMENT
                - CUSTOMER_RETURN
                - BUYER_CANCELED
                - OTHER
            transmissionStatus:
              type: string
              enum:
                - OK
                - ERROR
                - WAITING
            marketPlaceShipmentStatus:
              type: string
            invoice:
              $ref: '#/components/schemas/Invoice'
            deliveryStatus:
              type: string
              enum:
                - UNKNOWN
                - IN_TRANSIT
                - DELIVERED
                - HOLD_FOR_PICKUP
                - DELAYED
                - DELIVERED_LATE
            shipmentExceptionDate:
              type: string
              format: date-time
            shipmentExceptionDescription:
              type: string
            metadata:
              type: object
              properties:
                string:
                  type: string
            cancelDetails:
              type: string
            documentIntermediator:
              type: string
            intermediateRegistrationId:
              type: string
            documentPaymentInstitution:
              type: string
        - $ref: '#/components/schemas/OrderPost'
    OrderStatusUpdate:
      title: OrderStatusUpdate
      type: object
      x-examples:
        example-1:
          success: true
          errorMessage: string
          marketPlaceStatus: string
      properties:
        success:
          type: boolean
        errorMessage:
          type: string
          description: Mensagem com o motivo da não atualização do status do pedido
        marketPlaceStatus:
          type: string
          description: Status do pedido no Marketplace
      required:
        - success
        - marketPlaceStatus
      description: 'Quando o marketplace receber a notificação de atualização de um pedido, seja ele mudando para FATURADO, ENVIADO, CONCLUIDO ou CANCELADO no endpoint /updateOrderStatusInMarketPlace. Necessariamente o marketplace deve realizar o GET para consultar os dados do pedido e na sequencia utilizar do endpoint citado a cima, removendo a sinalização de sincronização e identificando qual o status do pedido no marketplace. Lembrando que caso não processe, o erro deve ser informado também nesse endpoint.'
    Page_Order:
      title: Page_Brand
      allOf:
        - properties:
            links:
              type: array
              description: Referências de paginação
              uniqueItems: false
              minItems: 1
              maxItems: 1
              items:
                $ref: '#/components/schemas/PageLinks'
            content:
              type: array
              description: Lista de marcas
              items:
                $ref: '#/components/schemas/Order'
            page:
              $ref: '#/components/schemas/PageMetadata'
      x-tags:
        - Marcas
      description: ''
      type: object
    PageLinks:
      title: PageLinks
      type: object
      x-tags:
        - page
        - pageable
      properties:
        rel:
          type: string
          description: Relacionamento do hyperlink
          example: next
        href:
          type: string
          description: Url de definição do recurso
          example: 'https://.../v2/component?limit=5&offset=5'
          format: uri
    PageMetadata:
      title: PageMetadata
      type: object
      properties:
        size:
          type: integer
          description: Tamanho da página
          format: int64
          minimum: 5
          readOnly: true
        totalElements:
          type: integer
          description: Total de elementos existentes
          format: int64
          minimum: 0
          readOnly: true
        totalPages:
          type: integer
          description: Total de páginas disponíveis
          format: int64
          minimum: 1
          readOnly: true
        number:
          type: integer
          description: Número da página atual
          format: int64
          minimum: 1
          readOnly: true
      x-tags:
        - page
        - pageable
    CanceledStatusDTO:
      title: CanceledStatusDTO
      type: object
      properties:
        date:
          type: string
          format: date-time
      x-examples:
        example-1:
          date: '2020-01-11T13:48:55-03:00:00'
    markAsShipped:
      description: ''
      type: object
      x-examples:
        example-1:
          status: SHIPPED
          url: 'https://teste.com.br'
          number: PR55887C12
          carrier: Total Express
          estimateDate: '2021-11-01T00:00:00-03:00'
          shippedDate: '2021-10-27T14:57:55-03:00'
      properties:
        status:
          type: string
          minLength: 1
          description: Status do pedido no ANYMARKET
          enum:
            - SHIPPED
        url:
          type: string
          minLength: 1
          description: URL para rastreio
        number:
          type: string
          minLength: 1
          description: codigo de rastreio
        carrier:
          type: string
          minLength: 1
          description: Transportadora
        estimateDate:
          type: string
          minLength: 1
          description: Data estimada de entrega
        shippedDate:
          type: string
          minLength: 1
          description: Data de envio
      required:
        - shippedDate
    markAsDelivered:
      description: ''
      type: object
      x-examples:
        example-1:
          deliveredDate: '2021-10-27T14:57:55-03:00'
      properties:
        deliveredDate:
          type: string
          minLength: 1
          description: Data de entrega
      required:
        - deliveredDate
    configuration:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 1
          oi: '12345678.'
          active: true
          templateId: 641
          accountName: Conta - TESTE
          marketplace: MARKETPLACE
          discountType: VALUE
          useSandbox: false
          accountDefault: true
          priceFactor: 1.5
          discountValue: 0
          updatePriceStockStatus: true
          additionOfFreight: 0
          fields:
            - value: '2000'
              key: shopId
            - value: LG1234567892346R-213987654
              key: anymarketToken
            - value: '12345678.'
              key: organizationId
          initialDateOrderImport: '2021-10-27'
      properties:
        id:
          type: number
          description: É o Id fornecido no saveAccount quando o seller ativa a integração no Anymarket.
        oi:
          type: string
          minLength: 1
          description: OI (Organization Id) do Seller
        active:
          type: boolean
          description: Informa se a integração esá Ativa (Booleano).
        templateId:
          type: number
          description: Id do template padrão
        accountName:
          type: string
          minLength: 1
          description: Nome da conta do Seller no Anymarket.
        marketplace:
          type: string
          minLength: 1
          description: Nome do próprio Marketplace.
        discountType:
          type: string
          minLength: 1
          description: Tipo de Desconto
          default: PERCENT
          enum:
            - PERCENT
            - VALUE
        useSandbox:
          type: boolean
          description: Informa se o uso é em Sandbox.
        accountDefault:
          type: boolean
          description: Informa a Conta Padrão.
        priceFactor:
          type: number
          description: Fator de Preço Multiplicador (Markup Adicional)
          format: double
        discountValue:
          type: number
          description: Valor de desconto.
          format: double
        updatePriceStockStatus:
          type: boolean
          description: 'Informa se irá atualizar Preço, Estoque e Status.'
        additionOfFreight:
          type: number
          description: Porcentagem adicional sobre a tabela de frete.
        fields:
          type: array
          uniqueItems: true
          minItems: 1
          description: Campos do módulo que são customizados para atender a autenticação do Seller ao Marketplace.
          items:
            type: object
            properties:
              value:
                type: string
                minLength: 1
              key:
                type: string
                minLength: 1
            required:
              - value
              - key
        initialDateOrderImport:
          type: string
          minLength: 1
          description: Data inicial para importação dos pedidos
      required:
        - id
        - oi
        - active
        - accountName
        - marketplace
        - discountType
        - useSandbox
        - accountDefault
        - priceFactor
        - discountValue
        - updatePriceStockStatus
        - additionOfFreight
        - fields
        - initialDateOrderImport
  parameters:
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        format: int64
        default: 1
        minimum: 1
        exclusiveMaximum: true
        example: 1
      description: Posição de início da paginação
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int64
        minimum: 5
        exclusiveMaximum: true
        default: 5
        example: 5
      description: Número máximo de marcas
    sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
      description: Atributo para ordenação
    appId:
      name: appId
      in: header
      required: true
      schema:
        type: string
    token:
      name: token
      in: header
      required: true
      schema:
        type: string
      description: token
  examples:
    brands_200:
      value:
        links:
          - rel: string
            href: string
        content:
          - rel: string
            href: string
        page:
          size: 0
          totalElements: 0
          totalPages: 0
          number: 0
