openapi: 3.0.0
info:
  title: remote
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /testIntegration:
    post:
      summary: Teste de Integração com marketplace
      operationId: post-testIntegration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
              examples:
                Example:
                  value: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModuleConfiguration'
            examples: {}
        description: Teste de Integração
      tags:
        - Configuração
      description: Teste de Integração com marketplace
  /saveAccount:
    post:
      summary: Salvar configurações de conta no marketplace
      operationId: post-testIntegration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
              examples:
                Example:
                  value: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModuleConfiguration'
            examples: {}
        description: Teste de Integração
      tags:
        - Configuração
      description: Salvar configurações de conta no marketplace
  '/product/{idProduct}':
    get:
      summary: Consulta produto no marketplace
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuMarketplace'
      operationId: get-product
      description: Consulta produto no marketplace
      parameters:
        - schema:
            type: integer
            format: int64
            minimum: 0
            exclusiveMaximum: true
          in: query
          name: idAccount
          description: Código da conta no marketplace
        - schema:
            type: string
            enum:
              - COST
              - SKU_MARKETPLACE
              - SKU
          in: query
          name: definitionScope
          description: Tipo da regra de preço do produto
    parameters:
      - schema:
          type: string
        name: idProduct
        in: path
        required: true
        description: Código do produto
  /brands:
    get:
      summary: Consulta marcas no marketplace
      tags: []
      operationId: get-brands
      description: Consulta marcas no marketplace
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
              examples:
                Example:
                  value:
                    - codeInMarketplace: string
                      name: string
  /categories:
    get:
      summary: Consulta categoria no marketplace
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
              examples:
                Example:
                  value:
                    - codeInMarketplace: string
                      name: string
      operationId: get-categories
      description: Consulta categoria no marketplace
      parameters:
        - schema:
            type: string
          in: query
          name: accountIdentifier
          description: Identificação da conta
  '/categories/bind/{idAnymarketCategory}':
    parameters:
      - schema:
          type: string
        name: idAnymarketCategory
        in: path
        required: true
        description: Código de categoria no Anymarket
    get:
      summary: Consulta vínculo de categoria no marketplace
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryAssociation'
              examples:
                Example:
                  value:
                    idCategoryMarketplace: string
                    idCategoryAnymarket: 0
                    accountIdentifier: string
      operationId: get-categories-bind-id
      description: Consulta vínculo de categoria no marketplace
      parameters:
        - schema:
            type: string
          in: query
          name: accountIdentifier
          description: Identificação da conta
  '/categories/attributes/{idAnymarketCategory}':
    parameters:
      - schema:
          type: string
        name: idAnymarketCategory
        in: path
        required: true
        description: Código de categoria no Anymarket
    get:
      summary: Consulta dos atributos vinculados à categoria
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryAttribute'
              examples:
                Example:
                  value:
                    - codeInMarketPlace: string
                      description: string
                      required: true
                      recommended: true
                      type: STRING_INPUT
                      values:
                        - codeInMarketplace: string
                          name: string
                      dataDefinitions:
                        - codeInMarketPlace: string
                          name: string
                          dataDefinitionType: STRING_INPUT
                          values:
                            - codeInMarketplace: string
                              name: string
      operationId: get-categories-attributes-id
      description: Consulta dos atributos vinculados à categoria
  /variations/types:
    get:
      summary: Consulta os tipos e valores possíveis para o seller realizar o de/para.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VariationType'
              examples:
                Example:
                  value:
                    - codeInMarketplace: string
                      name: string
                      values:
                        - codeInMarketplace: string
                          name: string
      operationId: get-variations-types
      description: Consulta os tipos e valores possíveis para o seller realizar o de/para.
  /canActive:
    post:
      summary: Validação das informações do Sku
      operationId: post-canActive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
              examples:
                Example:
                  value: Active
      description: |-
        A finalidade deste remote é informar uma previa do SKU que o seller está querendo transmitir para o marketplace. O JSON que é encaminhado no corpo da chamada contem os dados do SKU e dados do produto.
        Neste momento é esperado que o marketplace faça uma breve analise do conteúdo, validando assim informações pertinentes a criação do anuncio no marketplace, como por exemplo, se dados como vinculação de categoria, marca e variação foram realizados pelo seller.
        Em caso de sucesso o marketplace deve retornar um http status 200 e tendo como response body um valor booleano, em caso de negativa é esperado que o marketplace retorne o motivo, para assim o seller ter o retorno visual da negativa e aplicar as correções apresentadas.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SKU'
            examples:
              Example:
                value:
                  id: 0
                  partnerId: string
                  amount: 0
                  ean: string
                  title: string
                  price: 0
                  sellPrice: 0
                  additionalTime: 0
                  variations:
                    - id: 0
                      idInMarketplace: string
                      description: string
                      type:
                        id: 0
                        idInMarketplace: string
                        name: string
                        partnerId: string
                        visualVariation: true
                      partnerId: string
                  product:
                    id: 0
                    title: string
                    description: string
                    model: string
                    nbm:
                      id: string
                      description: string
                    videoUrl: string
                    definitionPriceScope: COST
                    characteristics:
                      - index: 0
                        name: string
                        value: string
                    origin:
                      id: 0
                      name: NACIONAL
                    category:
                      id: 0
                      idInMarketplace: string
                      name: string
                      path: string
                    height: 0
                    length: 0
                    width: 0
                    weight: 0
                    images:
                      - id: 0
                        index: 0
                        variation: string
                        thumbnailUrl: string
                        standardUrl: string
                        lowResolutionUrl: string
                        originalImage: string
                        url: string
                        statusMessage: string
                        status: UNPROCESSED
                        main: true
                        standardWidth: string
                        standardHeight: string
                        originalWidth: string
                        originalHeight: string
                    brand:
                      id: 0
                      idInMarketplace: string
                      name: string
                      partnerId: string
                    warrantyTime: 0
                    warrantyText: string
                    priceFactor: 0
                    calculatedPrice: true
                    hasVariations: true
                    gender: MALE
                    allowAutomaticSkuMarketplaceCreation: true
        description: ''
  '/getDefaultSkuFields/{idSku}':
    parameters:
      - schema:
          type: string
        name: idSku
        in: path
        required: true
        description: Código do Sku no Anymarket
    get:
      summary: Obter dados obrigatórios do SKU no marketplace
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  String:
                    type: string
              examples:
                example-1:
                  value:
                    EAN: '7894566666666'
                    title: Panela Elétrica de Arroz Visor Glass Philco Preta 220V
                    DISCOUNT_VALUE: '0'
                    DISCOUNT_TYPE: PERCENT
                    priceFactor: '1'
      operationId: get-getDefaultSkuFields-idSku
      parameters:
        - schema:
            type: string
          in: query
          name: idAccount
          description: Código da conta no marketplace
      description: |-
        Após o marketplace autorizar o envio do produto na requisição anterior (canActive), o ANYMARKET irá disparar uma chamada para obter alguns dados obrigatórios para criação da interface do anuncio no painel ANYMARKET.
        É necessário que o marketplace retorne o titulo do SKU, EAN e as informações default de preço
  /canSave:
    post:
      summary: Validações das informações da transmissão
      operationId: post-canSave
      responses:
        '200':
          description: OK
      description: |-
        Após as chamadas anteriores terem sido respondidas corretamente o seller terá uma visualização no ANYMARKET das informações do anuncio, podendo assim realizar edições no título, EAN e preço.
        Após o seller confirmar as informações ou realizar as devidas alterações será disparado esse request contendo o JSON com todas as informações atualizadas e demais informações da transmissão.
        É nesse momento em que o marketplace deve registrar as informações e aguardar a autorização do seller para ativação dentro do marketplace ou em caso de negativa é esperado que o marketplace retorne o motivo, para assim o seller ter o retorno visual da negativa e aplicar as correções apresentadas.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SkuMarketplaceCanSave'
        description: ''
components:
  schemas:
    Attributes:
      title: Attributes
      type: object
      properties:
        String:
          type: string
      examples:
        - cor: azul
          tamanho: grande
          material: inox
    AvailableStockDTO:
      title: AvailableStockDTO
      type: object
      properties:
        amount:
          type: number
          format: double
          minimum: 0
        availableAmount:
          type: number
          format: double
          minimum: 0
        cost:
          type: number
          format: double
          minimum: 0
        totalReservation:
          type: number
          format: double
          minimum: 0
        physicalAmount:
          type: number
          format: double
          minimum: 0
        reservedPending:
          type: number
          format: double
          minimum: 0
        reservedPaid:
          type: number
          format: double
          minimum: 0
        totalInInvoicedStatus:
          type: number
          format: double
          minimum: 0
        stockLocal:
          format: double
          type: string
        additionalTime:
          type: integer
          format: int32
          minimum: 0
          maximum: 999
    Brand:
      title: Brand
      type: object
      properties:
        codeInMarketplace:
          type: string
        name:
          type: string
      examples:
        - codeInMarketplace: string
          name: string
    Category:
      description: ''
      type: object
      properties:
        codeInMarketplace:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
      required:
        - codeInMarketplace
        - name
      x-examples:
        example-1:
          codeInMarketplace: string
          name: string
      title: Category
    CategoryAssociation:
      title: CategoryAssociation
      type: object
      properties:
        idCategoryMarketplace:
          type: string
        idCategoryAnymarket:
          type: integer
          format: int64
          minimum: 0
        accountIdentifier:
          type: string
    CategoryAttribute:
      description: ''
      type: object
      x-examples:
        example-1:
          codeInMarketPlace: '665'
          description: Sabor
          required: true
          recommended: false
          type: STRING_INPUT
      properties:
        codeInMarketPlace:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        required:
          type: boolean
        recommended:
          type: boolean
        type:
          type: string
          minLength: 1
          enum:
            - STRING_INPUT
            - SELECT_INPUT
            - NUMBER_INPUT
        values:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        dataDefinitions:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDataDefinition'
      required:
        - codeInMarketPlace
        - description
        - required
        - recommended
        - type
      examples:
        - codeInMarketPlace: string
          description: string
          required: true
          recommended: true
          type: STRING_INPUT
          values:
            - codeInMarketplace: string
              name: string
          dataDefinitions:
            - codeInMarketPlace: string
              name: string
              dataDefinitionType: STRING_INPUT
              values:
                - codeInMarketplace: string
                  name: string
      title: CategoryAttribute
    CategoryDataDefinition:
      title: CategoryDataDefinition
      type: object
      properties:
        codeInMarketPlace:
          type: string
        name:
          type: string
        dataDefinitionType:
          type: string
          enum:
            - STRING_INPUT
            - SELECT_INPUT
            - NUMBER_INPUT
        values:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    MarketPlace:
      title: MarketPlace
      type: string
      description: Identificador do Marketplace
      enum:
        - B2W
        - CNOVA
        - ECOMMERCE
        - MERCADO_LIVRE
        - WALMART
        - GFG
        - NETSHOES
        - VTEX;
      examples: []
    ModuleConfiguration:
      title: ModuleConfiguration
      type: object
      examples:
        - id: 0
          active: true
          templateId: 0
          accountName: string
          discountType: PERCENT
          useSandbox: true
          accountDefault: true
          priceFactor: 0
          discountValue: 0
          initialDateForOrderImport: 25-01-2021
          updatePriceStockStatus: true
          additionOfFreight: 0
          dynamicFields:
            field1: value1
            field2: value2
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
          description: Id do ANYMARKET
        active:
          type: boolean
          description: Status da conta
        templateId:
          type: integer
          format: int64
          minimum: 0
          description: Código do template padrão
        accountName:
          type: string
          minLength: 0
          maxLength: 255
          description: Nome do usuário no marketplace
        discountType:
          type: string
          minLength: 0
          maxLength: 255
          description: Tipo de desconto
          default: PERCENT
        useSandbox:
          type: boolean
          description: Informa se o uso é em Sandbox
        accountDefault:
          type: boolean
          description: Informa se a conta é a padrão para o marketplace
        priceFactor:
          type: number
          format: double
          minimum: 0
          description: Fator de preço
        discountValue:
          type: number
          format: double
          minimum: 0
          description: Valor padrão de desconto
        initialDateForOrderImport:
          type: string
          format: date
          pattern: '^\d{2}-\d{2}-\d{4}$'
          description: Data inicial para a importação de pedidos
          example: 25-01-2021
        updatePriceStockStatus:
          type: boolean
          description: Permite ou não atualizar o preço e status do estoque
        additionOfFreight:
          type: number
          format: double
          minimum: 0
          description: Valor adicional de frete
        dynamicFields:
          type: object
          description: Campos customizados para atender especifidade do MarketPlace
          properties:
            field:
              type: string
      required:
        - id
        - active
        - accountName
        - discountType
        - useSandbox
        - accountDefault
        - priceFactor
        - discountValue
        - initialDateForOrderImport
        - updatePriceStockStatus
        - additionOfFreight
    PriceScope:
      title: PriceScope
      type: string
    Product:
      description: ''
      type: object
      x-examples: {}
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        title:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        model:
          type: string
          minLength: 1
        nbm:
          type: object
          required:
            - id
            - description
          properties:
            id:
              type: string
              format: int64
            description:
              type: string
              minLength: 1
        videoUrl:
          format: int32
          type: string
        definitionPriceScope:
          type: string
          enum:
            - COST
            - SKU_MARKETPLACE
            - SKU
        characteristics:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              index:
                type: integer
                format: int32
                minimum: 0
              name:
                type: string
                minLength: 1
              value:
                type: string
                minLength: 1
            required:
              - index
              - name
              - value
        origin:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int32
              minimum: 0
            name:
              type: string
              minLength: 1
              enum:
                - NACIONAL
                - ESTRANGEIRA_IMPORTACAO_DIRETA
                - ESTRANGEIRA_ADQUIRIDA_NO_MERCADO_INTERNO
                - NACIONAL_IMPORTACAO_MAIS_40_PORCENTO
                - NACIONAL_CONFORMIDADE_AJUSTES
                - NACIONAL_IMPORTACAO_MENOS_40_PORCENTO
                - ESTRANGEIRA_SEM_SIMILAR_NACIONAL
                - ESTRANGEIRA_ADQUIRIDA_NO_MERCADO_INTERNO_SEM_SIMILAR
                - NACIONAL_IMPORTACAO_MAIS_70_PORCENTO
        category:
          type: object
          required:
            - id
            - idInMarketplace
            - name
            - path
          properties:
            id:
              type: integer
              format: int64
              minimum: 0
            idInMarketplace:
              type: string
              minLength: 1
            name:
              type: string
              minLength: 1
            path:
              type: string
              minLength: 1
        height:
          type: number
          format: double
          minimum: 0
        length:
          type: number
          format: double
          minimum: 0
        width:
          type: number
          format: double
          minimum: 0
        weight:
          type: number
          format: double
          minimum: 0
        images:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
                minimum: 0
              index:
                type: integer
                format: int32
                minimum: 0
              variation:
                type: string
                minLength: 1
              thumbnailUrl:
                type: string
                minLength: 1
              standardUrl:
                type: string
                minLength: 1
              lowResolutionUrl:
                type: string
                minLength: 1
              originalImage:
                type: string
                minLength: 1
              url:
                type: string
                minLength: 1
              statusMessage:
                type: string
              status:
                type: string
                minLength: 1
                enum:
                  - UNPROCESSED
                  - PROCESSED
                  - ERROR
              main:
                type: boolean
              standardWidth:
                type: string
              standardHeight:
                type: string
              originalWidth:
                type: string
              originalHeight:
                type: string
            required:
              - id
              - index
              - variation
              - thumbnailUrl
              - standardUrl
              - lowResolutionUrl
              - originalImage
              - url
              - status
              - main
              - standardWidth
              - standardHeight
              - originalWidth
              - originalHeight
        brand:
          type: object
          required:
            - id
            - idInMarketplace
            - name
            - partnerId
          properties:
            id:
              type: number
            idInMarketplace:
              type: string
              minLength: 1
            name:
              type: string
              minLength: 1
            partnerId:
              type: string
              minLength: 1
        warrantyTime:
          type: integer
          format: int32
          minimum: 0
          maximum: 999
        warrantyText:
          format: int32
          type: string
        priceFactor:
          type: number
          format: double
          minimum: 0
        calculatedPrice:
          format: double
          type: boolean
        hasVariations:
          format: double
          type: boolean
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - UNISSEX
            - BOY
            - GIRL
        allowAutomaticSkuMarketplaceCreation:
          type: boolean
      required:
        - id
        - title
        - description
        - model
        - nbm
        - videoUrl
        - definitionPriceScope
        - characteristics
        - origin
        - category
        - images
        - brand
        - warrantyTime
        - warrantyText
        - allowAutomaticSkuMarketplaceCreation
      title: Product
    SKU:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 33652426
          partnerId: '00889584736'
          amount: null
          ean: '7898414090938'
          title: Nicho Elegance-Castro - Nacar
          price: 399
          sellPrice: 399
          additionalTime: 0
      examples: []
      properties:
        id:
          type: integer
          format: int64
        partnerId:
          type: string
          minLength: 1
        amount:
          type: number
          format: double
          minimum: 0
        ean:
          type: string
          minLength: 1
        title:
          type: string
          minLength: 1
        price:
          type: number
          format: double
          minimum: 0
        sellPrice:
          type: number
          format: double
          minimum: 0
        additionalTime:
          type: integer
          format: int32
          minimum: 0
          maximum: 999
        variations:
          type: array
          items:
            $ref: '#/components/schemas/SkuVariation'
        product:
          $ref: '#/components/schemas/Product'
      required:
        - id
        - partnerId
        - amount
        - ean
        - title
        - price
        - sellPrice
        - additionalTime
      title: SKU
    SkuMarketplace:
      type: object
      description: ''
      examples:
        - id: 0
          idInMarketplace: string
          marketPlace: B2W
          index: 0
          publicationStatus: string
          marketplaceStatus: string
          transmissionStatus: string
          errorMsg: string
          skuMarketPlaceMessage:
            message: string
            key: string
            parameters:
              parameter1: value1
              parameter2: value2
          price: 0
          priceFactor: 1
          discountPrice: 0
          skuInMarketplace: string
          marketplaceItemCode: string
          fields:
            title: string
            template: string
            priceFactor: string
            DISCOUNT_TYPE: string
            DISCOUNT_VALUE: string
            HAS_DISCOUNT: string
            CONCAT_ATTRIBUTES: string
            delivery_type: string
            SHIPMENT: string
            crossDocking: string
            CUSTOM_DESCRIPTION: string
            EAN: string
            MANUFACTURING_TIME: string
            VALUE: string
            PERCENT: string
            bronze_price: string
            bronze_price_factor: string
            buying_mode: string
            category_with_variation: string
            condition: string
            free_price: string
            free_price_factor: string
            free_shipping: string
            gold_premium_price: string
            gold_premium_price_factor: string
            gold_price: string
            gold_price_factor: string
            gold_pro_price: string
            gold_pro_price_factor: string
            gold_special_price: string
            gold_special_price_factor: string
            listing_type_id: string
            shipping_local_pick_up: string
            shipping_mode: string
            silver_price: string
            silver_price_factor: string
          availableStock:
            amount: 0
            availableAmount: 0
            cost: 0
            totalReservation: 0
            physicalAmount: 0
            reservedPending: 0
            reservedPaid: 0
            totalInInvoicedStatus: 0
            stockLocal: string
            additionalTime: 0
          attributes:
            cor: azul
            tamanho: grande
            material: inox
          idAccount: 0
          accountName: string
          origin: BIND
          isCatalog: true
          permalink: string
          title: string
          ean: string
      properties:
        id:
          type: integer
          description: Id do anúncio no ANYMARKET
          format: int64
        idInMarketplace:
          type: string
          description: Id do anúncio no Marketplace
          maxLength: 255
          minLength: 0
        marketPlace:
          $ref: '#/components/schemas/MarketPlace'
        index:
          type: integer
          description: Índice do anúncio por Marketplace
          format: int64
        publicationStatus:
          type: string
          description: Status da publicação
        marketplaceStatus:
          type: string
          description: Status da publicação no marketplace
        transmissionStatus:
          type: string
          description: Status da publicação no marketplace
        errorMsg:
          type: string
        skuMarketPlaceMessage:
          $ref: '#/components/schemas/SkuMarketPlaceMessage'
        price:
          type: number
          description: Preço do anúncio
          format: double
          minimum: 0
        priceFactor:
          type: number
          description: Markup da transmissão
          format: double
          minimum: '00'
          example: 1
        discountPrice:
          type: number
          description: Preço com desconto do anúncio
          format: double
          minimum: 0
        skuInMarketplace:
          type: string
          description: Identificador da conta no marketplace
        marketplaceItemCode:
          type: string
          description: Identificador da conta no marketplace
        fields:
          $ref: '#/components/schemas/SkuMarketplaceField'
        availableStock:
          $ref: '#/components/schemas/AvailableStockDTO'
        attributes:
          $ref: '#/components/schemas/Attributes'
        idAccount:
          type: integer
          description: Identificador do SKU no marketplace
          format: int64
          minimum: 0
        accountName:
          type: string
          description: Identificador do SKU no marketplace
        origin:
          type: string
          description: Identificador do SKU no marketplace
          enum:
            - BIND
            - CREATE
        isCatalog:
          description: Código do anúncio no marketplace
          type: boolean
        permalink:
          description: Código do anúncio no marketplace
          type: string
        title:
          description: Código do anúncio no marketplace
          type: string
        ean:
          type: string
          description: Status da transmissão
      required:
        - id
        - marketPlace
        - index
        - publicationStatus
        - price
        - priceFactor
        - skuInMarketplace
        - marketplaceItemCode
        - fields
      title: SkuMarketplace
    SkuMarketPlaceMessage:
      title: SkuMarketPlaceMessage
      type: object
      properties:
        message:
          type: string
        key:
          type: string
        parameters:
          type: object
          properties:
            string:
              type: string
      examples:
        - message: string
          key: string
          parameters:
            parameter1: value1
            parameter2: value2
    SkuVariation:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 1456452
          description: Nacar
          type:
            id: 8260
            name: Cor
            partnerId: null
            visualVariation: true
            values: []
          partnerId: Nacar
      examples: []
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        idInMarketplace:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        type:
          $ref: '#/components/schemas/SkuVariationType'
        partnerId:
          type: string
          minLength: 1
      required:
        - id
        - idInMarketplace
        - description
        - type
        - partnerId
      title: SkuVariation
    SkuMarketplaceField:
      type: object
      description: Informações especificas do anúncio por marketplace
      properties:
        title:
          type: string
          description: 'B2W,WALMART,MERCADO LIVRE'
          format: int64
        template:
          type: string
          description: MERCADO LIVRE
        priceFactor:
          type: string
          description: 'B2W,CNOVA,WALMART,ECOMMERCE,MERCADO LIVRE'
          format: int64
        DISCOUNT_TYPE:
          type: string
          description: 'B2W,CNOVA,WALMART,ECOMMERCE,MERCADO LIVRE'
          format: int64
        DISCOUNT_VALUE:
          type: string
          description: 'B2W,CNOVA,WALMART,ECOMMERCE,MERCADO LIVRE'
          format: int64
        HAS_DISCOUNT:
          type: string
          description: 'B2W,CNOVA,ECOMMERCE'
          format: int64
        CONCAT_ATTRIBUTES:
          type: string
          description: B2W
          format: int64
        delivery_type:
          type: string
          description: B2W
          format: int64
        SHIPMENT:
          type: string
          description: B2W
          format: int64
        crossDocking:
          type: string
          description: B2W
          format: int64
        CUSTOM_DESCRIPTION:
          type: string
          description: B2W
          format: int64
        EAN:
          type: string
          description: 'B2W,CNOVA'
          format: int64
        MANUFACTURING_TIME:
          type: string
          description: CNOVA
          format: int64
        VALUE:
          type: string
          description: 'WALMART,MERCADO LIVRE'
          format: int64
        PERCENT:
          type: string
          description: 'WALMART,MERCADO LIVRE'
          format: int64
        bronze_price:
          type: string
          description: MERCADO LIVRE
          format: int64
        bronze_price_factor:
          type: string
          description: MERCADO LIVRE
          format: int64
        buying_mode:
          type: string
          description: MERCADO LIVRE
          format: int64
        category_with_variation:
          type: string
          description: MERCADO LIVRE
          format: int64
        condition:
          type: string
          description: MERCADO LIVRE
          format: int64
        free_price:
          type: string
          description: MERCADO LIVRE
          format: int64
        free_price_factor:
          type: string
          description: MERCADO LIVRE
          format: int64
        free_shipping:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_premium_price:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_premium_price_factor:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_price:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_price_factor:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_pro_price:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_pro_price_factor:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_special_price:
          type: string
          description: MERCADO LIVRE
          format: int64
        gold_special_price_factor:
          type: string
          description: MERCADO LIVRE
          format: int64
        listing_type_id:
          type: string
          description: MERCADO LIVRE
          format: int64
        shipping_local_pick_up:
          type: string
          description: MERCADO LIVRE
          format: int64
        shipping_mode:
          type: string
          description: MERCADO LIVRE
          format: int64
        silver_price:
          type: string
          description: MERCADO LIVRE
          format: int64
        silver_price_factor:
          type: string
          description: MERCADO LIVRE
          format: int64
      title: SkuMarketplaceField
    SkuVariationType:
      title: SkuVariationType
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        idInMarketplace:
          type: string
        name:
          type: string
        partnerId:
          type: string
        visualVariation:
          type: boolean
    VariationType:
      description: ''
      type: object
      x-examples:
        example-1:
          codeInMarketplace: COLOR_VARIANT
          name: Cor
          values:
            - codeInMarketplace: string
              name: string
            - codeInMarketplace: BLUE
              name: Azul
      examples: []
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        idInMarketplace:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        partnerId:
          type: string
          minLength: 1
        visualVariation:
          type: boolean
        values:
          type: array
          items:
            $ref: '#/components/schemas/Variation'
      required:
        - id
        - idInMarketplace
        - name
        - partnerId
        - visualVariation
      title: VariationType
    Variation:
      description: ''
      type: object
      x-examples:
        example-1:
          codeInMarketplace: COLOR_VARIANT
          name: Cor
          values:
            - codeInMarketplace: string
              name: string
            - codeInMarketplace: BLUE
              name: Azul
      examples: []
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        idInMarketplace:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        type:
          $ref: '#/components/schemas/VariationType'
        partnerId:
          type: string
          minLength: 1
      required:
        - idInMarketplace
        - description
        - partnerId
      title: Variation
    SkuMarketplaceCanSave:
      description: ''
      type: object
      x-examples: {}
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
          exclusiveMaximum: true
        mainSkuMarketplace:
          type: integer
          format: int64
          minimum: 0
          exclusiveMaximum: true
        catalog:
          type: boolean
        idInMarketplace:
          type: string
          minLength: 1
        status:
          type: string
          minLength: 1
        marketplaceStatus:
          type: string
          minLength: 1
        transmissionStatus:
          type: string
          minLength: 1
        errorMsg:
          type: string
        skuMarketPlaceMessage:
          $ref: '#/components/schemas/SkuMarketPlaceMessage'
        idInSite:
          type: string
        fields:
          $ref: '#/components/schemas/SkuMarketplaceField'
        isCatalog:
          type: boolean
        permalink:
          type: string
        title:
          type: string
        ean:
          type: string
        skuInMarketplace:
          type: string
          minLength: 1
        priceFactor:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        price:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        discountPrice:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        idAccount:
          type: integer
          format: int64
          minimum: 0
          exclusiveMaximum: true
        accountName:
          type: string
          minLength: 1
        marketPlace:
          $ref: '#/components/schemas/MarketPlace'
        stock:
          $ref: '#/components/schemas/Stock'
        attributes:
          type: object
          required:
            - ATRIBUTO
            - TESTE
            - NOVO ATRIBUTO
          properties:
            ATRIBUTO:
              type: string
              minLength: 1
            TESTE:
              type: string
              minLength: 1
            NOVO ATRIBUTO:
              type: string
              minLength: 1
        sku:
          $ref: '#/components/schemas/SKU'
      required:
        - catalog
        - idInMarketplace
        - status
        - marketplaceStatus
        - transmissionStatus
        - fields
        - isCatalog
        - skuInMarketplace
        - priceFactor
        - price
        - discountPrice
        - idAccount
        - accountName
        - attributes
    Stock:
      title: Stock
      type: object
      properties:
        amount:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        availableAmount:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        cost:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        totalReservation:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        physicalAmount:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        reservedPending:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        reservedPaid:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        totalInInvoicedStatus:
          type: number
          format: double
          minimum: 0
          exclusiveMaximum: true
        stockLocal:
          type: string
        additionalTime:
          type: integer
          format: int32
          minimum: 0
          exclusiveMaximum: false
          maximum: 999
